name: build and deploy - mkdocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          cd docs
          pip install -r requirements.txt
          mkdocs gh-deploy --force --clean --verbose